name: CICD

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t harmanxze/nexa-backend:latest .

      - name: Publish image to docker hub
        run: docker push harmanxze/nexa-backend:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: docker pull harmanxze/nexa-backend:latest

      - name: Delete old container
        run: docker rm -f nexa-server-container || true

      - name: Run docker container
        run: |
          docker run -d \
            -p 3001:3001 \
            --name nexa-server-container \
            --restart unless-stopped \
            -e PORT=${{ secrets.PORT }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e NODE_ENV=${{ secrets.NODE_ENV }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            -e RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            -e RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} \
            -e RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} \
            -e FRONTEND_DOMAIN=${{ secrets.FRONTEND_DOMAIN }} \
            -e LOG_DIRECTORY=${{ secrets.LOG_DIRECTORY }} \
            harmanxze/nexa-backend:latest
